<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FenixServer</RootNamespace>
    <AssemblyName>FenixServerS7</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>All;Debug;Release</Configurations>
    <StartupObject>FenixServer.App</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>HttpServer.ico</ApplicationIcon>
    <Version>4.2.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModbusMasterASCII\ModbusMasterASCII.csproj" />
    <ProjectReference Include="..\ModbusMasterRTU\ModbusMasterRTU.csproj" />
    <ProjectReference Include="..\ModbusMasterTCP\ModbusMasterTCP.csproj" />
    <ProjectReference Include="..\ProjectDataLib\ProjectDataLib.csproj" />
    <ProjectReference Include="..\S7-300-400 Ethernet\S7-300-400 Ethernet.csproj" />
    <ProjectReference Include="..\FenixServer.Web\FenixServer.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.3" />
    <PackageReference Include="System.Data.SQLite.EF6" Version="2.0.3" />
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>
</Project>

