<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <StartupObject>FenixServer.Web.EntryPoint</StartupObject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateXunitEntryPoint>false</GenerateXunitEntryPoint>
    <IsTestProject>false</IsTestProject>
    <IsPackable>false</IsPackable>
    <Version>4.1.0</Version>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <FileVersion>4.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModbusMasterASCII\ModbusMasterASCII.csproj" />
    <ProjectReference Include="..\ModbusMasterRTU\ModbusMasterRTU.csproj" />
    <ProjectReference Include="..\ModbusMasterTCP\ModbusMasterTCP.csproj" />
    <ProjectReference Include="..\ProjectDataLib.Test\ProjectDataLib.Test.csproj" />
    <ProjectReference Include="..\ProjectDataLib\ProjectDataLib.csproj" />
    <ProjectReference Include="..\S7-300-400 Ethernet\S7-300-400 Ethernet.csproj" />
  </ItemGroup>
</Project>
