<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <StartupObject>FenixServer.Web.EntryPoint</StartupObject>
    <Version>4.2.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModbusMasterASCII\ModbusMasterASCII.csproj" />
    <ProjectReference Include="..\ModbusMasterRTU\ModbusMasterRTU.csproj" />
    <ProjectReference Include="..\ModbusMasterTCP\ModbusMasterTCP.csproj" />
    <ProjectReference Include="..\ProjectDataLib\ProjectDataLib.csproj" />
    <ProjectReference Include="..\S7-300-400 Ethernet\S7-300-400 Ethernet.csproj" />
  </ItemGroup>
</Project>

